definitions:
  github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.Item:
    properties:
      description:
        type: string
      id:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.Order:
    properties:
      currencyUnit:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.Item'
        type: array
      status:
        type: string
      total:
        type: number
    type: object
  github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.UpdateOrder:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.User:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact:
    email: fazilkp2000@gmail.com
    name: API Support
    url: https://fazilnbr.github.io/mypeosolal.web.portfolio/
  description: This is a sample Order Management Sytem. You can visit the GitHub repository
    at https://github.com/fazilnbr/SA01-OrderManagement
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Gin Seller App Order Management Sytem
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      operationId: authentication login
      parameters:
      - description: auth login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      summary: authentication login
      tags:
      - Authentication
  /auth/register:
    post:
      operationId: SignUp authentication
      parameters:
      - description: Worker Login
        in: body
        name: WorkerLogin
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.User'
          - properties:
              password:
                type: string
              username:
                type: string
            type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      summary: SignUp for users
      tags:
      - Authentication
  /auth/token-refresh:
    get:
      operationId: Refresh access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      security:
      - BearerAuth: []
      summary: Refresh The Access Token
      tags:
      - Authentication
  /order:
    get:
      operationId: Fetchorder
      parameters:
      - description: 'Status : '
        in: query
        name: status
        type: string
      - description: 'Min Total : '
        in: query
        name: mintotal
        type: string
      - description: 'Max Total : '
        in: query
        name: maxtolat
        type: string
      - description: 'Sort By : '
        in: query
        name: sortby
        type: string
      - description: 'Sort Order : '
        in: query
        name: sortorder
        type: string
      - description: 'Page : '
        in: query
        name: page
        required: true
        type: string
      - description: 'Pagesize : '
        in: query
        name: pagesize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      security:
      - BearerAuth: []
      summary: Fetch Order
      tags:
      - Order
    post:
      operationId: createorder
      parameters:
      - description: Order Detials
        in: body
        name: orderdetials
        required: true
        schema:
          $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      security:
      - BearerAuth: []
      summary: Create Order
      tags:
      - Order
    put:
      operationId: Updateorder
      parameters:
      - description: Update Order Detials
        in: body
        name: updateorderdetials
        required: true
        schema:
          $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_domain.UpdateOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/github_com_fazilnbr_SA01-OrderManagement_SA01-grpc-api-gateway_pkg_utils_response.Response'
      security:
      - BearerAuth: []
      summary: Update Order
      tags:
      - Order
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
