// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/api"
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/api/services"
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/config"
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/db"
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/repository"
	"github.com/fazilnbr/SA01-OrderManagement/SA01-grpc-order-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := repository.NewOrderRepository(gormDB)
	orderUseCase := usecase.NewOrderUseCase(orderRepository)
	orderService := services.NewOrderService(orderUseCase)
	serverHTTP := http.NewServerHTTP(orderService)
	return serverHTTP, nil
}
